version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
