repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.8
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]
      - id: ruff-format

  - repo: https://github.com/stefmolin/exif-stripper
    rev: 0.1.2
    hooks:
      - id: strip-exif

  - repo: local
    hooks:
      - id: resize-logos
        name: Resize Logos
        entry: scripts/resize_images.py
        language: python
        language_version: python3
        additional_dependencies: [pillow, pyprojroot]
        types: [image]
        pass_filenames: false
