title:            Biscuit Crumbs
description:      A place to collect my biscuit crumbs.
url:              # Site url.
signoff:          Marcus Mo
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          /
  - name:         Email
    url:          mailto:marcusmo88@gmail.com
    external:     true
  - name:         GitHub
    url:          http://github.com/gobbledygook88
    external:     true
pygments:         true
permalink:        pretty
markdown:         rdiscount
rdiscount:
  extensions:     [smart]
