title:            Biscuit Crumbs
description:      A place to collect my biscuit crumbs.
url:              http://marcusmo.co.uk
signoff:          Marcus Mo
disqus_shortname: biscuitcrumbs
google_analytics: 'UA-24583920-1'

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          /
  - name:         Work
    url:          /work
pygments:         true
permalink:        pretty
markdown:         kramdown
#rdiscount:
#  extensions:     [smart]
