title:            Biscuit Crumbs
description:      A place to collect my biscuit crumbs.
url:              # Site url.
signoff:          Marcus Mo
disqus_shortname: biscuitcrumbs
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          /
  - name:         Work
    url:          /work
pygments:         true
permalink:        pretty
markdown:         kramdown
#rdiscount:
#  extensions:     [smart]
