title:            Biscuit Crumbs
description:      A place to collect my biscuit crumbs.
url:              http://marcusmo.co.uk
signoff:          Marcus Mo
disqus_shortname: biscuitcrumbs
google_analytics: 'UA-24583920-1'

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          /
  - name:         Collections
    url:          /collections
  - name:         Github
    url:          "https://github.com/gobbledygook88"
    external:     true
pygments:         true
permalink:        /:categories/:title/
markdown:         kramdown
#rdiscount:
#  extensions:     [smart]
